AGENT:
  BATCH_SIZE: 64
  EPSILON: 0.9
  EPSILON_DECAY_RATE: 1.0e-05
  GAMMA: 0.95
  LR: 0.0001
  MEMORY_CAPACITY: 10000
  MINIMUN_EPSILON: 0.05
  TARGET_REPLACE_ITER: 100
NETWORK:
  MLP:
    FC1: 512
    FC2: 256
RANDOM_SEED: 10
