RANDOM_SEED: 10

AGENT:
  BATCH_SIZE: 64
  LR: 0.00001
  EPSILON: 0.9
  MINIMUN_EPSILON: 0.05
  EPSILON_DECAY_RATE: 1e-5
  GAMMA: 0.95
  TARGET_REPLACE_ITER: 100
  MEMORY_CAPACITY: 10000

NETWORK:
  MLP:
    FC1: 512
    FC2: 512