RANDOM_SEED: 10

AGENT:
  BATCH_SIZE: 32
  LR: 0.0001
  EPSILON: 0.5
  MINIMUN_EPSILON: 0.01
  EPSILON_DECAY_RATE: 1e-5
  GAMMA: 0.95
  TARGET_REPLACE_ITER: 100
  MEMORY_CAPACITY: 1000

NETWORK:
  MLP:
    FC1: 256
    FC2: 256